### ISSUE TITLE
No such file or directory:".../results/HDFS/embedding.model"

### ISSUE THREAD

**Issue by hahaymm** [WeibinMeng/Log2Vec#1]
Traceback (most recent call last):
  File "code/mimick/make_dataset.py", line 54, in <module>
    words, embs = read_text_embs(options.vectors)
  File "/Users/name/Desktop/Log2Vec-master/code/mimick/my_utils.py", line 49, in read_text_embs
    with codecs.open(filename, "r", "utf-8") as f:
  File "/opt/anaconda3/lib/python3.7/codecs.py", line 904, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/name/Desktop/Log2Vec-master/results/HDFS/embedding.model'

请问这是怎么回事？

**Comment by WeibinMeng** [comment]
cd ./LRWE/src/ 
make #make before you run

(I have added it in readme)

**Comment by yanli0514** [comment]
make以后仍然报错，找不到embedding.model文件，请问如何解决？
Traceback (most recent call last):
  File "code/mimick/make_dataset.py", line 54, in <module>
    words, embs = read_text_embs(options.vectors)
  File "/root/Log2Vec-master/code/mimick/my_utils.py", line 49, in read_text_embs
    with codecs.open(filename, "r", "utf-8") as f:
  File "/usr/lib64/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/root/Log2Vec-master/results/HDFS/embedding.model'
